---
name: homepage
label: Homepage
fields:
  - name: nav
    type: field_group
    label: Navbar
    fields:
      - label: Wordmark
        name: wordmark
        type: field_group
        fields:
          - label: Icon
            name: icon
            type: field_group
            fields:
              - name: color
                label: Color
                type: select
                config:
                  source:
                    type: simple
                  options:
                    - primary
                    - blue
                    - teal
                    - green
                    - red
                    - pink
                    - purple
                    - orange
                    - yellow
              - name: name
                label: Icon
                type: select
                config:
                  source:
                    type: simple
                  options:
                    - random
                    - FiAperture
                    - BiCodeBlock
                    - BiLike
                    - BiMapAlt
                    - BiPalette
                    - BiPieChartAlt2
                    - BiPin
                    - BiShield
                    - BiSlider
                    - BiStore
                    - BiTennisBall
                    - BiTestTube
                    - BiTrophy
                    - BiUserCircle
                    - BiBeer
                    - BiChat
                    - BiCloud
                    - BiCoffeeTogo
                    - BiWorld
              - name: style
                label: Style
                type: select
                config:
                  source:
                    type: simple
                  options:
                    - circle
                    - float
          - label: Name
            name: name
            type: text
      - label: Nav Items
        name: items
        type: field_group_list
        fields:
          - label: Label
            name: label
            type: text
          - label: Link
            name: link
            type: text
  - name: blocks
    label: Page Sections
    type: blocks
    template_types:
      - hero
      - testimonial
      - features
  - name: navlist
    label: Nav List
    type: blocks
    template_types:
      - nav
  - name: footer
    label: Footer
    type: field_group
    fields:
      - name: social
        label: Social Media
        type: field_group
        fields:
          - name: facebook
            label: Facebook
            type: text
          - name: twitter
            label: Twitter
            type: text
          - name: instagram
            label: Instagram
            type: text
          - name: github
            label: Github
            type: text
