name: Pull Request
on: [pull_request]

jobs:
  tinkering:
    runs-on: ubuntu-latest
    if: contains(github.ref, "primitive")
    steps:
    - run: echo "I only run if the branch has primitive in its name!"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn ci:build
      - name: Test
        run: yarn ci:test
